/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.epu.view;


import com.epu.controller.AccountController;
import com.epu.model.Account;
import com.epu.model.SessionManager;
import java.awt.Color;
import javax.swing.JFrame;

public class FrmMain extends JFrame {
    
    PanelQLSP pageQLSP = new PanelQLSP();    
    PanelQLInventory pageQLTonKho = new PanelQLInventory();
    PanelQLNhap pageQLN = new PanelQLNhap();
    PanelQLXuat pageQLX = new PanelQLXuat();
    PanelBaoCaoThongKe pageBaoCaoThongKe = new PanelBaoCaoThongKe();
    PanelQLAccount pageAccount = new PanelQLAccount();
    
    
    public FrmMain() {
        initComponents();
        mainLayer.add(pageQLSP);        
        mainLayer.add(pageQLTonKho);
        mainLayer.add(pageQLN);
        mainLayer.add(pageQLX);
        mainLayer.add(pageBaoCaoThongKe);
        mainLayer.add(pageAccount);
        
        pageQLSP.setVisible(true);
        pageQLTonKho.setVisible(false);
        pageQLN.setVisible(false);
        pageQLX.setVisible(false);
        pageBaoCaoThongKe.setVisible(false);
        pageAccount.setVisible(false);
        
        btnPageManageProduct.setBackground(Color.GRAY);
        btnPageManageInventory.setBackground(new Color(0,102,102));
        btnPageManageNhap.setBackground(new Color(0,102,102));
        btnPageManageXuat.setBackground(new Color(0,102,102));
        btnPageBaoCaoThongKe.setBackground(new Color(0,102,102));
        btnPageTaiKhoan.setBackground(new Color(0,102,102));
        
        Account acc = new AccountController().getAccountById(SessionManager.getInstance().getAccountId());
        lbAccountName.setText(acc.getAccountName());
        
        btnPageBaoCaoThongKe.setForeground(Color.WHITE);
        btnPageManageInventory.setForeground(Color.WHITE);
        btnPageManageNhap.setForeground(Color.WHITE);
        btnPageManageProduct.setForeground(Color.WHITE);
        btnPageManageXuat.setForeground(Color.WHITE);
        btnPageTaiKhoan.setForeground(Color.WHITE);
        
        
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbPageTitle = new javax.swing.JLabel();
        lbAccountName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnPageManageProduct = new javax.swing.JButton();
        btnPageManageInventory = new javax.swing.JButton();
        btnPageManageNhap = new javax.swing.JButton();
        btnPageBaoCaoThongKe = new javax.swing.JButton();
        btnPageManageXuat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnPageTaiKhoan = new javax.swing.JButton();
        mainLayer = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setPreferredSize(new java.awt.Dimension(1555, 840));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name Comany");

        lbPageTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbPageTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbPageTitle.setText("Quản Lý Sản Phẩm");

        lbAccountName.setForeground(new java.awt.Color(255, 255, 255));
        lbAccountName.setText("lbAccountName");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lbPageTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbPageTitle)
                .addGap(17, 17, 17))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        btnPageManageProduct.setText("Quản Lý Sản Phẩm");
        btnPageManageProduct.setBorder(null);
        btnPageManageProduct.setFocusPainted(false);
        btnPageManageProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPageManageProductActionPerformed(evt);
            }
        });

        btnPageManageInventory.setText("Quản Lý Tồn Kho");
        btnPageManageInventory.setBorder(null);
        btnPageManageInventory.setFocusPainted(false);
        btnPageManageInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPageManageInventoryActionPerformed(evt);
            }
        });

        btnPageManageNhap.setText("Quản Lý Nhập");
        btnPageManageNhap.setBorder(null);
        btnPageManageNhap.setFocusPainted(false);
        btnPageManageNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPageManageNhapActionPerformed(evt);
            }
        });

        btnPageBaoCaoThongKe.setText("Báo Cáo Thống Kê");
        btnPageBaoCaoThongKe.setBorder(null);
        btnPageBaoCaoThongKe.setFocusPainted(false);
        btnPageBaoCaoThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPageBaoCaoThongKeActionPerformed(evt);
            }
        });

        btnPageManageXuat.setText("Quản Lý Xuất");
        btnPageManageXuat.setBorder(null);
        btnPageManageXuat.setFocusPainted(false);
        btnPageManageXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPageManageXuatActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Đăng Xuất");

        btnPageTaiKhoan.setText("Quản lý tài khoản");
        btnPageTaiKhoan.setBorder(null);
        btnPageTaiKhoan.setFocusPainted(false);
        btnPageTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPageTaiKhoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPageManageProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPageManageInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPageManageNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPageBaoCaoThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPageManageXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(btnPageTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnPageManageProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnPageManageInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnPageManageNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnPageManageXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnPageBaoCaoThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnPageTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );

        mainLayer.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainLayer, javax.swing.GroupLayout.PREFERRED_SIZE, 1429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainLayer, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPageManageProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPageManageProductActionPerformed
        pageQLSP.setVisible(true);
        pageQLTonKho.setVisible(false);
        pageQLN.setVisible(false);
        pageQLX.setVisible(false);
        pageBaoCaoThongKe.setVisible(false);
        pageAccount.setVisible(false);
        
        btnPageManageProduct.setBackground(Color.GRAY);
        btnPageManageInventory.setBackground(new Color(0,102,102));
        btnPageManageNhap.setBackground(new Color(0,102,102));
        btnPageManageNhap.setBackground(new Color(0,102,102));
        btnPageManageNhap.setBackground(new Color(0,102,102));
        btnPageTaiKhoan.setBackground(new Color(0,102,102));
        
        lbPageTitle.setText("Quản Lý Sản Phẩm");
    }//GEN-LAST:event_btnPageManageProductActionPerformed

    private void btnPageManageInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPageManageInventoryActionPerformed
        pageQLSP.setVisible(false);
        pageQLTonKho.setVisible(true);
        pageQLN.setVisible(false);
        pageQLX.setVisible(false);
        pageBaoCaoThongKe.setVisible(false);
        pageAccount.setVisible(false);
        
        btnPageManageProduct.setBackground(new Color(0,102,102));
        btnPageManageInventory.setBackground(Color.GRAY);
        btnPageManageNhap.setBackground(new Color(0,102,102));
        btnPageManageXuat.setBackground(new Color(0,102,102));
        btnPageBaoCaoThongKe.setBackground(new Color(0,102,102));
        btnPageTaiKhoan.setBackground(new Color(0,102,102));
        
        lbPageTitle.setText("Quản Lý Tồn Kho");
    }//GEN-LAST:event_btnPageManageInventoryActionPerformed

    private void btnPageManageNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPageManageNhapActionPerformed
        pageQLSP.setVisible(false);
        pageQLTonKho.setVisible(false);
        pageQLN.setVisible(true);
        pageQLX.setVisible(false);
        pageBaoCaoThongKe.setVisible(false);
        pageAccount.setVisible(false);
        
        btnPageManageProduct.setBackground(new Color(0,102,102));
        btnPageManageInventory.setBackground(new Color(0,102,102));
        btnPageManageNhap.setBackground(Color.GRAY);
        btnPageManageXuat.setBackground(new Color(0,102,102));
        btnPageBaoCaoThongKe.setBackground(new Color(0,102,102));
        btnPageTaiKhoan.setBackground(new Color(0,102,102));
        
        lbPageTitle.setText("Quản Lý Nhập");
    }//GEN-LAST:event_btnPageManageNhapActionPerformed

    private void btnPageBaoCaoThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPageBaoCaoThongKeActionPerformed
        pageQLSP.setVisible(false);
        pageQLTonKho.setVisible(false);
        pageQLN.setVisible(false);
        pageQLX.setVisible(false);
        pageBaoCaoThongKe.setVisible(true);
        pageAccount.setVisible(false);
        
        btnPageManageProduct.setBackground(new Color(0,102,102));
        btnPageManageInventory.setBackground(new Color(0,102,102));
        btnPageManageNhap.setBackground(new Color(0,102,102));
        btnPageManageXuat.setBackground(new Color(0,102,102));
        btnPageBaoCaoThongKe.setBackground(Color.GRAY);
        btnPageTaiKhoan.setBackground(new Color(0,102,102));
        
        lbPageTitle.setText("Báo Cáo Thống Kê");
    }//GEN-LAST:event_btnPageBaoCaoThongKeActionPerformed

    private void btnPageManageXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPageManageXuatActionPerformed
        pageQLSP.setVisible(false);
        pageQLTonKho.setVisible(false);
        pageQLN.setVisible(false);
        pageQLX.setVisible(true);
        pageBaoCaoThongKe.setVisible(false);
        pageAccount.setVisible(false);
        
        btnPageManageProduct.setBackground(new Color(0,102,102));
        btnPageManageInventory.setBackground(new Color(0,102,102));
        btnPageManageNhap.setBackground(new Color(0,102,102));
        btnPageManageXuat.setBackground(Color.GRAY);
        btnPageBaoCaoThongKe.setBackground(new Color(0,102,102));
        btnPageTaiKhoan.setBackground(new Color(0,102,102));
        
        lbPageTitle.setText("Quản Lý Xuất");
    }//GEN-LAST:event_btnPageManageXuatActionPerformed

    private void btnPageTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPageTaiKhoanActionPerformed
        pageQLSP.setVisible(false);
        pageQLTonKho.setVisible(false);
        pageQLN.setVisible(false);
        pageQLX.setVisible(false);
        pageBaoCaoThongKe.setVisible(false);
        pageAccount.setVisible(true);
        
        btnPageManageProduct.setBackground(new Color(0,102,102));
        btnPageManageInventory.setBackground(new Color(0,102,102));
        btnPageManageNhap.setBackground(new Color(0,102,102));
        btnPageManageXuat.setBackground(new Color(0,102,102));
        btnPageBaoCaoThongKe.setBackground(new Color(0,102,102));
        btnPageTaiKhoan.setBackground(Color.GRAY);
        
        lbPageTitle.setText("Quản Lý Tài Khoản");
    }//GEN-LAST:event_btnPageTaiKhoanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPageBaoCaoThongKe;
    private javax.swing.JButton btnPageManageInventory;
    private javax.swing.JButton btnPageManageNhap;
    private javax.swing.JButton btnPageManageProduct;
    private javax.swing.JButton btnPageManageXuat;
    private javax.swing.JButton btnPageTaiKhoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbAccountName;
    private javax.swing.JLabel lbPageTitle;
    private javax.swing.JLayeredPane mainLayer;
    // End of variables declaration//GEN-END:variables
}
