/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.epu.view;

import com.epu.controller.InventoryController;
import com.epu.controller.ProductController;
import com.epu.controller.ShelfController;
import com.epu.controller.WareHouseController;
import com.epu.model.ExcelInventory;
import com.epu.model.Inventory;
import com.epu.model.Product;
import com.epu.model.WareHouse;
import java.awt.CardLayout;
import java.io.File;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class PanelQLInventory extends javax.swing.JPanel {

    Inventory choosenInven = null;
    boolean checkEdit = false;
    public PanelQLInventory() {
        initComponents();
        // Panel chính quản lý Tồn kho
        fillDataCbboxKhoHang();
        fillDataTableSPTrongKho(String.valueOf(cbboxKhoHang.getSelectedItem()));
        // Panel quản lý thêm sản phẩm mới vào tồn kho   
        fillDataCbboxProductPanelInsert();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbboxKhoHang = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSPTonKho = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnPageInsertTonKho = new javax.swing.JButton();
        btnPageUpdateTonKho = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        mainLayout = new javax.swing.JPanel();
        defaultPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        editPanel = new javax.swing.JPanel();
        lbEdit = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        cbboxProduct = new javax.swing.JComboBox<>();
        txtWareHouseId = new javax.swing.JTextField();
        cbboxShelf = new javax.swing.JComboBox<>();
        lbErrorChooseProduct = new javax.swing.JLabel();
        lbErrorWareHouseId = new javax.swing.JLabel();
        lbErrorChooseShelf = new javax.swing.JLabel();
        lbErrorQuantity = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1130, 700));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Chọn Kho :");

        cbboxKhoHang.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbboxKhoHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbboxKhoHangActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Sản Phẩm Tồn Kho", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        tableSPTonKho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableSPTonKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSPTonKhoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableSPTonKho);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Các Thao Tác"));

        btnPageInsertTonKho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPageInsertTonKho.setText("Insert");
        btnPageInsertTonKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPageInsertTonKhoActionPerformed(evt);
            }
        });

        btnPageUpdateTonKho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPageUpdateTonKho.setText("Update");
        btnPageUpdateTonKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPageUpdateTonKhoActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnExport.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnExport.setText("Export Excel");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        btnImport.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnImport.setText("Import Excel");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPageInsertTonKho)
                    .addComponent(btnReset))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPageUpdateTonKho)
                    .addComponent(btnImport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExport)
                    .addComponent(btnDelete))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnPageUpdateTonKho)
                    .addComponent(btnPageInsertTonKho))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExport)
                    .addComponent(btnImport)
                    .addComponent(btnReset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainLayout.setBackground(new java.awt.Color(255, 255, 255));
        mainLayout.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Form Chức Năng"));
        mainLayout.setLayout(new java.awt.CardLayout());

        defaultPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Click Chọn Chức Năng Để Hiển Thị Form Thiết Kế");

        javax.swing.GroupLayout defaultPanelLayout = new javax.swing.GroupLayout(defaultPanel);
        defaultPanel.setLayout(defaultPanelLayout);
        defaultPanelLayout.setHorizontalGroup(
            defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defaultPanelLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel2)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        defaultPanelLayout.setVerticalGroup(
            defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defaultPanelLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel2)
                .addContainerGap(388, Short.MAX_VALUE))
        );

        mainLayout.add(defaultPanel, "defaultPanel");

        editPanel.setBackground(new java.awt.Color(255, 204, 204));

        lbEdit.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbEdit.setText("Quản lý hàng tồn kho");

        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Product :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("WareHouse :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Shelf :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Quantity :");

        txtQuantity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cbboxProduct.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtWareHouseId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cbboxShelf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lbErrorChooseProduct.setForeground(new java.awt.Color(255, 51, 51));

        lbErrorWareHouseId.setForeground(new java.awt.Color(255, 51, 51));

        lbErrorChooseShelf.setForeground(new java.awt.Color(255, 51, 51));

        lbErrorQuantity.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout editPanelLayout = new javax.swing.GroupLayout(editPanel);
        editPanel.setLayout(editPanelLayout);
        editPanelLayout.setHorizontalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelLayout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(lbEdit)
                .addGap(190, 190, 190))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbboxProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbboxShelf, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbErrorChooseShelf, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbErrorChooseProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(editPanelLayout.createSequentialGroup()
                                .addComponent(lbErrorWareHouseId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(2, 2, 2))
                            .addComponent(lbErrorQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(txtWareHouseId)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(132, 132, 132))
        );
        editPanelLayout.setVerticalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbEdit)
                .addGap(48, 48, 48)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(cbboxProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbErrorChooseProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(txtWareHouseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbErrorWareHouseId, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(cbboxShelf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbErrorChooseShelf, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbErrorQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        mainLayout.add(editPanel, "editPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbboxKhoHang, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addComponent(mainLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(mainLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbboxKhoHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Panel Main
    public void fillDataCbboxKhoHang()
    {
        DefaultComboBoxModel cbboxModel = (DefaultComboBoxModel) cbboxKhoHang.getModel();   
        for(var w : new WareHouseController().getAll())
            cbboxModel.addElement(w.getWareHouseName());
    }
    public void fillDataTableSPTrongKho(String choosenWareHouseName)
    {
        int WareHouseId = getWareHouseIdIsChoosen(choosenWareHouseName);
        
        List<Inventory> listInventoryByWareHouseId = new InventoryController().getByWareHouseId(WareHouseId);
        DefaultTableModel tableModel = (DefaultTableModel) tableSPTonKho.getModel();
        String[] columnName = {"InventoryId","ProductId","WareHouseId","ShelfId","Quantity"};
        tableModel.setDataVector(new Object[][]{}, columnName);
        
        for(var i : listInventoryByWareHouseId)
        {
            Object[] rowData = {i.getInventyId(),i.getProductId(),i.getWareHouseId(),i.getShelfId(),i.getQuantity()};
            tableModel.addRow(rowData);
            
        }   
    } 
    public int getWareHouseIdIsChoosen(String wareHouseName)
    {
        int WareHouseId = 0;
        List<WareHouse> whs = new WareHouseController().getAll();
        for(var w : whs)
        {
            if(w.getWareHouseName().equals(wareHouseName))
                WareHouseId = w.getWareHouseId();
        } 
        return WareHouseId;
    }
    
    // Panel Insert
    public void fillDataCbboxProductPanelInsert()
    {
        // Fill Data Product
        List<Product> prs = new ProductController().getAll();
        
        DefaultComboBoxModel cbboxModelProduct = (DefaultComboBoxModel) cbboxProduct.getModel();
        for(var p : prs)
            cbboxModelProduct.addElement(p.getProductName());
        
    }
    // Nút chuyển hướng qua Panel Edit - Thêm 
    private void btnPageInsertTonKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPageInsertTonKhoActionPerformed
        CardLayout cl = (CardLayout) mainLayout.getLayout();
        cl.show(mainLayout, "editPanel");
        checkEdit = false;
        lbEdit.setText("THÊM MỚI TỒN KHO");
    }//GEN-LAST:event_btnPageInsertTonKhoActionPerformed
    // Nút chuyển hướng qua Panel Edit - Sửa 
    private void btnPageUpdateTonKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPageUpdateTonKhoActionPerformed

        if(this.tableSPTonKho.getSelectedRow() < 0)
            JOptionPane.showMessageDialog(this, "Hãy chọn Iventory cần sửa !");
        else 
        {
            
            CardLayout cl = (CardLayout) mainLayout.getLayout();
            cl.show(mainLayout, "editPanel");
            checkEdit = true;
            lbEdit.setText("SỬA ĐỔI TỒN KHO");
            txtQuantity.setText(String.valueOf(choosenInven.getQuantity()));
            txtWareHouseId.setText(String.valueOf(choosenInven.getWareHouseId()));
            List<Product> prs = new ProductController().getAll();
            String proName = "";
            for(var p : prs)
                if(p.getProductId() == choosenInven.getProductId())
                {
                    proName = p.getProductName();
                    break;
                }
            
            cbboxProduct.setSelectedItem(proName);
            
            cbboxShelf.setSelectedItem(choosenInven.getShelfId());
            
            cbboxKhoHang.setEnabled(false);
        }
    }//GEN-LAST:event_btnPageUpdateTonKhoActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if(this.tableSPTonKho.getSelectedRow() < 0)
            JOptionPane.showMessageDialog(this, "Hãy chọn Iventory cần xóa !");
        else
        {
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắn xóa không", "Xác nhận xóa Inventory", JOptionPane.YES_NO_OPTION);
            if(confirm == JOptionPane.YES_OPTION)
            {
                if(new InventoryController().Delete(choosenInven.getInventyId()))
                {
                    JOptionPane.showMessageDialog(this, "Delete Success!");
                    fillDataTableSPTrongKho(String.valueOf(cbboxKhoHang.getSelectedItem()));
                }
                
                else
                    JOptionPane.showMessageDialog(this, "Delete Success!");
            }
            
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        btnPageInsertTonKho.setEnabled(true);
        cbboxKhoHang.setEnabled(true);
        cbboxKhoHang.setSelectedIndex(0);
        cbboxProduct.setSelectedIndex(0);
        cbboxKhoHangActionPerformed(evt);
        txtQuantity.setText("");
        txtWareHouseId.setText(String.valueOf(getWareHouseIdIsChoosen((String) cbboxKhoHang.getSelectedItem())));
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        JFileChooser fchoose = new JFileChooser();
        fchoose.setDialogTitle("Chọn file Excel muốn import");
        int result = fchoose.showOpenDialog(this);
        if(result == JFileChooser.APPROVE_OPTION)
        {
            String filePath = fchoose.getSelectedFile().getAbsolutePath();
            List<Inventory> in = new ExcelInventory().importToExcel(filePath);
            
            boolean ck = true;
            for(var i : in)
                if(new InventoryController().Insert(i) == false)
                    ck = false; 
            
            if(ck)
            {
                JOptionPane.showMessageDialog(this, "Import thành công");
                fillDataTableSPTrongKho(String.valueOf(cbboxKhoHang.getSelectedItem()));
            }
            else
                JOptionPane.showMessageDialog(this, "Import thất bại");
            
            
        }
    }//GEN-LAST:event_btnImportActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // Tạo ra fileChooser để lưu file
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn nơi lưu file Excel");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Excel Files","xlsx" ,"xls") );
        int userSelect = fileChooser.showSaveDialog(this);
        
        if(userSelect == JFileChooser.APPROVE_OPTION)
        {
            File fileSave = fileChooser.getSelectedFile();
            String filePath = fileSave.getAbsolutePath();
            if(!filePath.endsWith(".xlsx"))
                filePath += ".xlsx";
            
            new ExcelInventory().exportToExcel(filePath, tableSPTonKho, "Inventory of "+String.valueOf(cbboxKhoHang.getSelectedItem()));
            JOptionPane.showMessageDialog(this, "Xuất data thành công");  
        }   
    }//GEN-LAST:event_btnExportActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // Insert
        if(checkEdit == false)
        {
            int quantity = Integer.parseInt(txtQuantity.getText());
            int WareHouseId = Integer.parseInt(txtWareHouseId.getText());
            String choosenPName = String.valueOf(cbboxProduct.getSelectedItem());
            int productId = 0;
            List<Product> list = new ProductController().getAll();
            for(var p : list)
                if(p.getProductName().equals(choosenPName))
                {
                    productId = p.getProductId();
                    break;
                }
            int shelfId = (int) (cbboxShelf.getSelectedItem());
            Inventory i = new Inventory(productId, WareHouseId, shelfId, quantity);
            if(new InventoryController().Insert(i))
            {
                JOptionPane.showMessageDialog(this, "Insert Success!");
                txtQuantity.setText("");
                
                cbboxProduct.setSelectedIndex(0);
                cbboxShelf.setSelectedIndex(0);
                fillDataTableSPTrongKho(String.valueOf(cbboxKhoHang.getSelectedItem()));
            }
            else 
                JOptionPane.showMessageDialog(this, "Insert Fail!");
            
            
        } // Update
        else {
            int quantity = Integer.parseInt(txtQuantity.getText());
            int WareHouseId = Integer.parseInt(txtWareHouseId.getText());
            String choosenPName = String.valueOf(cbboxProduct.getSelectedItem());
            int productId = 0;
            List<Product> list = new ProductController().getAll();
            for(var p : list)
                if(p.getProductName().equals(choosenPName))
                {
                    productId = p.getProductId();
                    break;
                }
            int shelfId = (int) (cbboxShelf.getSelectedItem());
            Inventory i = new Inventory(choosenInven.getInventyId(), productId, WareHouseId, shelfId, quantity);
            if(new InventoryController().Update(i))
            {
                JOptionPane.showMessageDialog(this, "Update Success!");
                txtQuantity.setText("");
                cbboxProduct.setSelectedIndex(0);
                cbboxShelf.setSelectedIndex(0);
                fillDataTableSPTrongKho(String.valueOf(cbboxKhoHang.getSelectedItem()));
            }
            else 
                JOptionPane.showMessageDialog(this, "Update Fail!");
        }
        
        
    }//GEN-LAST:event_btnSaveActionPerformed
    // Event Click vào TableInventory Theo Kho
    private void tableSPTonKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSPTonKhoMouseClicked
        int row = this.tableSPTonKho.getSelectedRow();
        int mtk = (int) (this.tableSPTonKho.getModel().getValueAt(row, 0));
        choosenInven =  new InventoryController().getById(mtk);
        btnPageInsertTonKho.setEnabled(false);
              
    }//GEN-LAST:event_tableSPTonKhoMouseClicked

    private void cbboxKhoHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbboxKhoHangActionPerformed
 
        fillDataTableSPTrongKho(String.valueOf(cbboxKhoHang.getSelectedItem()));
        // Gán id cho khoId 
        int WareHouseId = getWareHouseIdIsChoosen(String.valueOf(cbboxKhoHang.getSelectedItem())); 
        txtWareHouseId.setText(String.valueOf(WareHouseId));
        txtWareHouseId.setEnabled(false);
        // Fill Data Combobox Shelf theo WareHouse
        cbboxShelf.removeAllItems();
        DefaultComboBoxModel cbboxModelShelf = (DefaultComboBoxModel) cbboxShelf.getModel();
        
        for(var s : new ShelfController().getByWareHouseId(WareHouseId))
            cbboxModelShelf.addElement(s.getShelfId());
    }//GEN-LAST:event_cbboxKhoHangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnPageInsertTonKho;
    private javax.swing.JButton btnPageUpdateTonKho;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbboxKhoHang;
    private javax.swing.JComboBox<String> cbboxProduct;
    private javax.swing.JComboBox<String> cbboxShelf;
    private javax.swing.JPanel defaultPanel;
    private javax.swing.JPanel editPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbEdit;
    private javax.swing.JLabel lbErrorChooseProduct;
    private javax.swing.JLabel lbErrorChooseShelf;
    private javax.swing.JLabel lbErrorQuantity;
    private javax.swing.JLabel lbErrorWareHouseId;
    private javax.swing.JPanel mainLayout;
    private javax.swing.JTable tableSPTonKho;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtWareHouseId;
    // End of variables declaration//GEN-END:variables
}
